### ISSUE TITLE
Dynamic whatsapp contact us fixed button

### ISSUE THREAD

**Issue by ryumada** [garasijogi/mamoto-website#30]
![image](https://user-images.githubusercontent.com/28515686/135275333-edb08034-b382-4848-9516-8877cdecd2ce.png)

It seems like the whatsapp contact us button is too big for mobile view, how about do we make it more dynamic using bootstrap grid?

**Comment by algorithmsEvolve** [comment]
fixed on branch https://github.com/garasijogi/mamoto-website/tree/fix/jumbotron-and-portfolio with this commit https://github.com/garasijogi/mamoto-website/commit/8a563eb7e562c1a1499fd242c620b06a8a5728c5
