### ISSUE TITLE
Background image doesn't act like background

### ISSUE THREAD

**Issue by ryumada** [garasijogi/mamoto-website#31]
![screenshots](https://user-images.githubusercontent.com/28515686/135276818-c708c1bb-0583-47ff-b13c-4f71cef9e1a8.jpg)

Background wedding ring placed on the bottom of the page in mobile view. Whereas in desktop view, it acts pretty well.

**Comment by algorithmsEvolve** [comment]
fixed on branch https://github.com/garasijogi/mamoto-website/tree/fix/jumbotron-and-portfolio with this commit https://github.com/garasijogi/mamoto-website/commit/c87cacbb40100c18cbb97bf387ab5af2dfd59c7c
