### ISSUE TITLE
Foto Jumbotron kurang HD

### ISSUE THREAD

**Issue by komarambon** [garasijogi/mamoto-website#32]
Foto yg di jumbotron masi pecah, bang nanda kasi keringanan juga si kalo gamau ribet, nanti ukuran size foto yg buat di jumbotron ngikutin aja sama size websitenya.
@algorithmsEvolve

**Comment by algorithmsEvolve** [comment]
fixed on branch https://github.com/garasijogi/mamoto-website/tree/fix/jumbotron-and-portfolio with this commit https://github.com/garasijogi/mamoto-website/commit/a56174509b3352ea3eeabf0620c1c6ff408c64af
