### ISSUE TITLE
the website icon is too small, and it looks like poop i don't like it

### ISSUE THREAD

**Issue by komarambon** [garasijogi/mamoto-website#33]
Ini icon websitenya diganti ke logo mamoto aja ya, kecil aja gapapa yg penting kan mamoto, daripada icon tai (literally) ini. Di figma ada kok logo mamoto nya. Icon pas jadi admin dan pas jadi client samain aja pake logo mamoto
![image](https://user-images.githubusercontent.com/49584637/135306626-e1961487-230b-481e-b804-d8186f7e058b.png)

**Comment by algorithmsEvolve** [comment]
fixed on branch https://github.com/garasijogi/mamoto-website/tree/fix/jumbotron-and-portfolio with this commit: https://github.com/garasijogi/mamoto-website/commit/f5122ec4bdeded0c40dedd531fff7bc808f6ec60
