### ISSUE TITLE
East Jakarta and West Jakarta pop out of nowhere

### ISSUE THREAD

**Issue by komarambon** [garasijogi/mamoto-website#34]
Itu lokasi jakarta timur ambilnya darimana ya? Gue mau edit di kelola portfolio juga gaada opsinya. Kalo mau yg “venue” di bagian kelola portfolio diganti jadi “Tempat” nanti dari kolom itu aja yg ditampilin di halaman portfolio
![image](https://user-images.githubusercontent.com/49584637/135307034-d507ca16-051c-4b6e-b2a6-33837cab8b00.png)
![image](https://user-images.githubusercontent.com/49584637/135307055-f6d046cb-1d00-40dd-b52c-d4db5b9813df.png)
![image](https://user-images.githubusercontent.com/49584637/135307082-60bd4f54-b800-4a3f-9757-0dd0cc7bf6e0.png)

**Comment by algorithmsEvolve** [comment]
fixed on branch https://github.com/garasijogi/mamoto-website/tree/fix/jumbotron-and-portfolio with this commit https://github.com/garasijogi/mamoto-website/commit/e8bb8055980bd8866969a912960b567982ebb58c
