### ISSUE TITLE
Delete "pesanan" in admin page

### ISSUE THREAD

**Issue by komarambon** [garasijogi/mamoto-website#35]
Kolom pesanan di admin dihapus aja soalnya kan nanti booknow langsung lari ke wa

**Comment by algorithmsEvolve** [comment]
fixed on branch https://github.com/garasijogi/mamoto-website/tree/fix/jumbotron-and-portfolio with this commit https://github.com/garasijogi/mamoto-website/commit/304841f112dea6b23abb9005c09be4568b7854d7
