### ISSUE TITLE
browse video in edit portfolio

### ISSUE THREAD

**Issue by komarambon** [garasijogi/mamoto-website#36]
•	Pas mau edit portfolio, videonya jadi suruh pilih browse video, bukan masukkan link youtube kayak pas mau entry awal
![image](https://user-images.githubusercontent.com/49584637/135308088-c2e70be9-2205-4ba8-bc3d-a615294e6093.png)

**Comment by algorithmsEvolve** [comment]
fixed on branch https://github.com/garasijogi/mamoto-website/tree/fix/jumbotron-and-portfolio with this commit https://github.com/garasijogi/mamoto-website/commit/047df2285007fa23efdcb90fca6ae907bdbae067
