### ISSUE TITLE
"kritik dan saran" appear in user page

### ISSUE THREAD

**Issue by komarambon** [garasijogi/mamoto-website#37]
Yang kesan jasa mamoto aja yg ditampilin, kritik dan saran gausah muncul di home
![image](https://user-images.githubusercontent.com/49584637/135308388-6408a070-5094-4e3a-9f3f-d6874a81004c.png)
![image](https://user-images.githubusercontent.com/49584637/135308372-8f4f7b6f-0129-472c-9805-3f40cfbf8b31.png)
![image](https://user-images.githubusercontent.com/49584637/135308400-431142a8-7250-433a-a886-99fdf20e2c00.png)

**Comment by algorithmsEvolve** [comment]
fixed on branch https://github.com/garasijogi/mamoto-website/tree/fix/jumbotron-and-portfolio with this commit https://github.com/garasijogi/mamoto-website/commit/edb3f824295859b9e4535ceb5ce4491c27cf20bd
