### ISSUE TITLE
reset feedback error 500

### ISSUE THREAD

**Issue by komarambon** [garasijogi/mamoto-website#38]
•	Saat mau reset feedback tapi isi feedbacknya kosong, halamannya jadi error server 500
![image](https://user-images.githubusercontent.com/49584637/135308620-8583bb14-1fe3-4038-b5eb-ee71ddd2e2b8.png)
![image](https://user-images.githubusercontent.com/49584637/135308605-5c9ac226-20db-4cf3-89e1-0feb6af44048.png)
Gini jadinya. Kira2 bisa dibuat warning aja gitu “tidak ada feedback untuk direset” atau gimana yg gampang

**Comment by algorithmsEvolve** [comment]
fixed on branch https://github.com/garasijogi/mamoto-website/commit/edb3f824295859b9e4535ceb5ce4491c27cf20bd with this commit https://github.com/garasijogi/mamoto-website/commit/19400cec76190561b773d5620ae66d24d58c2d19
