### ISSUE TITLE
Foto menjadi horizontal semua di halaman portfolio

### ISSUE THREAD

**Issue by komarambon** [garasijogi/mamoto-website#44]
maafin bar QA gagal ini ketinggalan mulu
![image](https://user-images.githubusercontent.com/49584637/135591102-b12605d4-c20f-4025-9b33-334767e9a37e.png)

**Comment by algorithmsEvolve** [comment]
fixed on branch https://github.com/garasijogi/mamoto-website/tree/fix/portfolio with this commit https://github.com/garasijogi/mamoto-website/commit/f60e61f0a750ebbbd615cfb4e1a1ed85076b7f73
