### ISSUE TITLE
sorting portfolio, newest portfolio on top, date ascending

### ISSUE THREAD

**Issue by komarambon** [garasijogi/mamoto-website#45]
yg terakhir bar semoga bener deh
![Uploading image.png…]()

**Comment by algorithmsEvolve** [comment]
fixed on branch https://github.com/garasijogi/mamoto-website/tree/fix/portfolio with this commit https://github.com/garasijogi/mamoto-website/commit/47bbb7bdda860f420dd404ad2b71b2d248d7d9d7
