### ISSUE TITLE
itu logo2 di home page masih dirasa terlalu akbar

### ISSUE THREAD

**Issue by komarambon** [garasijogi/mamoto-website#49]
logo mamoto di home page dan button contact us dirasa masih besar, minta dikecilin sesuai contoh yg beliau kasih
from this
![image](https://user-images.githubusercontent.com/49584637/135655726-a4543361-55b4-43cd-8add-bfc0b73fda43.png)
to this
![image](https://user-images.githubusercontent.com/49584637/135655511-03de2407-f1a9-45f2-90a0-f238c09f9eba.png)

**Comment by algorithmsEvolve** [comment]
fixed on branch https://github.com/garasijogi/mamoto-website/tree/fix/portfolio with this commit https://github.com/garasijogi/mamoto-website/commit/443331e4e175d8988d9345d9b2f24a0925113e56
