### ISSUE TITLE
lokasi portfolio gaikut ke halaman home

### ISSUE THREAD

**Issue by komarambon** [garasijogi/mamoto-website#51]
itu bar yg tadi di grup, biar ga lupa aja

**Comment by algorithmsEvolve** [comment]
fixed on branch https://github.com/garasijogi/mamoto-website/tree/fix/portfolio with this commit https://github.com/garasijogi/mamoto-website/commit/d84d2f0d6f4b9d511fb6022c6212bd8ec69d07c9
